# **Project Name**    - PhonePe Transaction Insights

##### **Project Type**    - EDA
##### **Contribution**    - Individual

# **Project Summary -**

The rapid growth of digital payment platforms such as PhonePe has significantly transformed financial transactions in India, making it essential to analyze user behavior, transaction patterns, and regional performance to improve services and strategic decision-making. This project focuses on analyzing aggregated transaction, user, insurance, and mapping data to derive meaningful insights that can support business growth, customer engagement, and operational efficiency. The primary objective is to understand how different regions, categories, and user groups contribute to overall platform activity and to identify key trends that can guide future improvements.

The project addresses multiple business use cases, including customer segmentation, fraud detection, geographical insights, payment performance evaluation, user engagement optimization, product development, insurance analysis, marketing optimization, trend analysis, and competitive benchmarking. By segmenting users based on transaction behavior, businesses can design personalized marketing strategies and improve customer retention. Transaction pattern analysis also helps in identifying anomalies that may indicate fraudulent activity, ensuring a secure payment ecosystem. Geographical analysis enables the identification of high-performing and underpenetrated regions, which supports targeted expansion and resource allocation.

To achieve these objectives, the data was first extracted from a GitHub repository containing structured PhonePe transaction datasets. The data was then loaded into a relational SQL database to ensure efficient storage and querying. Multiple tables were created to organize the data into aggregated, map, and top-level categories for users, transactions, and insurance information. Aggregated tables stored summarized user and transaction data, map tables captured state and district-level distribution of transaction values, and top tables highlighted the highest-performing users, regions, and categories.

Once the database was structured, SQL queries were used to extract relevant insights for analysis. The processed data was then analyzed using Python libraries such as Pandas for data manipulation and Plotly for visualization. Various charts including bar plots, pie charts, scatter plots, heatmaps, and line graphs were used to represent transaction trends, user engagement patterns, brand performance, and geographical distribution. These visualizations helped in identifying key patterns such as dominant states, high-performing brands, and variations in transaction types across regions.

A Streamlit-based interactive dashboard was developed to present the findings in a user-friendly manner, enabling real-time exploration of insights. This dashboard allows users to dynamically analyze transaction trends, compare regional performance, and understand category-wise contributions.

From the analysis, several important insights were derived. A small number of states and brands were found to contribute significantly to overall transaction volume, indicating concentrated usage patterns. Transaction trends showed consistent growth in user activity, although revenue growth was not always proportional, suggesting variations in transaction value behavior. Additionally, differences in regional adoption highlighted opportunities for expansion in underperforming areas.

Overall, the project demonstrates how data-driven analysis can be effectively used to understand complex digital payment ecosystems. The insights generated can support better decision-making in customer segmentation, marketing strategies, product development, and regional expansion. By leveraging these findings, businesses can enhance user engagement, optimize revenue generation, and ensure sustainable long-term growth in the evolving digital financial landscape.

# **GitHub Link -**

https://github.com/AkhilaRao0002/PhonePe-transaction-insights

# **Problem Statement**

With the increasing reliance on digital payment systems like PhonePe, understanding the dynamics of transactions, user engagement, and insurance-related data is crucial for improving services and targeting users effectively. This project aims to analyze and visualize aggregated values of payment categories, create maps for total values at state and district levels, and identify top-performing states, districts, and pin codes

#### **Define Your Business Objective?**

 *   **Customer Segmentation**: Segment users based on spending behavior and transaction patterns to enable personalized marketing and targeted customer engagement strategies.
*   **Fraud Detection**: Identify unusual transaction patterns and anomalies to detect and prevent fraudulent activities, ensuring secure and reliable digital payments.
*   **Geographical Insights**: Analyze transaction trends across states and districts to identify high-performing and underpenetrated regions for targeted expansion.
*   **Payment Performance analysis**: Evaluate the usage and growth of different payment categories to optimize investments and enhance platform offerings.
*   **User Engagement optimization**: Monitor user activity, app opens, and transaction frequency to develop strategies that improve user retention and satisfaction.
*   **Product Development strategy**: Leverage data insights to design and enhance features, improving user experience and meeting evolving customer needs.
*   **Insurance business Insights**: Analyze insurance transaction data to identify growth opportunities and improve product offerings in the insurance segment.
*   **Marketing Optimization**: Tailor marketing campaigns based on user behavior, regional trends, and transaction patterns to maximize conversion and ROI.
*   **Trend Analysis**:Examine transaction and user growth trends over time to forecast demand and support strategic decision-making.
*   **Competitive Benchmarking**: Compare platform performance across regions and categories to identify strengths, weaknesses, and areas for improvement.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries

In [2]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import json
import glob

### Dataset Loading

In [3]:
# Load Dataset
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
base_path = "/content/drive/MyDrive/Internship projects/Phone Pe project - Labmentix Internship/data-csv"

In [6]:
import pandas as pd
import glob
import os

base_path = "/content/drive/MyDrive/Internship projects/Phone Pe project - Labmentix Internship/data-csv"
output_path = "/content/drive/MyDrive/Internship projects/Phone Pe project - Labmentix Internship/cleaned_data"

os.makedirs(output_path, exist_ok=True)

def extract_metadata(file_path):
    parts = file_path.lower().split("/")

    year = None
    quarter = None
    state = None
    country = None

    for part in parts:
        if part.isdigit() and len(part) == 4:
            year = int(part)
        elif part.endswith(".csv"):
            quarter = int(part.replace(".csv", ""))

    if "state" in parts:
        idx = parts.index("state")
        if idx + 1 < len(parts):
            state = parts[idx + 1]

    if "country" in parts:
        idx = parts.index("country")
        if idx + 1 < len(parts):
            country = parts[idx + 1]

    return year, quarter, state, country


def process_folder(main_folder, sub_folder):
    output_file = f"{output_path}/{main_folder}_{sub_folder}.csv"

    # ✅ Skip if already exists
    if os.path.exists(output_file):
        print(f"⏭️ Skipping (already exists): {output_file}")
        return

    pattern = f"{base_path}/{main_folder}/{sub_folder}/**/*.csv"
    files = glob.glob(pattern, recursive=True)

    dfs = []

    for file in files:
        try:
            df = pd.read_csv(file)

            year, quarter, state, country = extract_metadata(file)

            df["year"] = year
            df["quarter"] = quarter
            df["state"] = state
            df["country"] = country

            dfs.append(df)

        except Exception as e:
            print(f"Error in {file}: {e}")

    if dfs:
        final_df = pd.concat(dfs, ignore_index=True)
        final_df.to_csv(output_file, index=False)

        print(f"✅ Created: {output_file} | Shape: {final_df.shape}")


# 🔥 Run for all 9 combinations
main_folders = ["aggregated", "map", "top"]
sub_folders = ["insurance", "transaction", "user"]

for main in main_folders:
    for sub in sub_folders:
        process_folder(main, sub)

⏭️ Skipping (already exists): /content/drive/MyDrive/Internship projects/Phone Pe project - Labmentix Internship/cleaned_data/aggregated_insurance.csv
⏭️ Skipping (already exists): /content/drive/MyDrive/Internship projects/Phone Pe project - Labmentix Internship/cleaned_data/aggregated_transaction.csv
⏭️ Skipping (already exists): /content/drive/MyDrive/Internship projects/Phone Pe project - Labmentix Internship/cleaned_data/aggregated_user.csv
⏭️ Skipping (already exists): /content/drive/MyDrive/Internship projects/Phone Pe project - Labmentix Internship/cleaned_data/map_insurance.csv
⏭️ Skipping (already exists): /content/drive/MyDrive/Internship projects/Phone Pe project - Labmentix Internship/cleaned_data/map_transaction.csv
⏭️ Skipping (already exists): /content/drive/MyDrive/Internship projects/Phone Pe project - Labmentix Internship/cleaned_data/map_user.csv
⏭️ Skipping (already exists): /content/drive/MyDrive/Internship projects/Phone Pe project - Labmentix Internship/cleaned_data/top_insurance.csv
⏭️ Skipping (already exists): /content/drive/MyDrive/Internship projects/Phone Pe project - Labmentix Internship/cleaned_data/top_transaction.csv
⏭️ Skipping (already exists): /content/drive/MyDrive/Internship projects/Phone Pe project - Labmentix Internship/cleaned_data/top_user.csv

### Dataset First View

In [5]:
import pandas as pd
import os

output_path = "/content/drive/MyDrive/Internship projects/Phone Pe project - Labmentix Internship/cleaned_data"

files = [
    "aggregated_insurance.csv",
    "aggregated_transaction.csv",
    "aggregated_user.csv",
    "map_insurance.csv",
    "map_transaction.csv",
    "map_user.csv",
    "top_insurance.csv",
    "top_transaction.csv",
    "top_user.csv"
]

In [6]:
# Dataset first look
for file in files:
    file_path = os.path.join(output_path, file)

    print(f"\n📂 {file}")

    df = pd.read_csv(file_path)

    display(df.head())

📂 aggregated_insurance.csv

,type,count,amount,state,year,quarter,source,category,country,date,avg_transaction_value,growth
0,insurance,185348,33732166.0,All,2020,2,aggregated,insurance,india,2020-Q2,181.993688,NaN
1,insurance,354284,89495076.0,All,2020,3,aggregated,insurance,india,2020-Q3,252.608292,0.911453
2,insurance,248626,170979933.0,All,2020,4,aggregated,insurance,india,2020-Q4,687.699328,-0.298230
3,insurance,318119,206307024.0,All,2021,1,aggregated,insurance,india,2021-Q1,648.521541,0.279508
4,insurance,363989,295066678.0,All,2021,2,aggregated,insurance,india,2021-Q2,810.647239,0.144191

📂 aggregated_transaction.csv

,type,count,amount,state,year,quarter,source,category,country,date,avg_transaction_value,growth
0,recharge & bill payments,72550406,1.447271e+10,All,2018,1,aggregated,transaction,india,2018-Q1,199.484942,NaN
1,peer-to-peer payments,46982705,1.472459e+11,All,2018,1,aggregated,transaction,india,2018-Q1,3134.044401,-0.352413
2,merchant payments,5368669,4.656679e+09,All,2018,1,aggregated,transaction,india,2018-Q1,867.380521,-0.885731
3,financial services,3762820,8.158531e+08,All,2018,1,aggregated,transaction,india,2018-Q1,216.819594,-0.299115
4,others,5761576,4.643217e+09,All,2018,1,aggregated,transaction,india,2018-Q1,805.893613,0.531186

📂 aggregated_user.csv

,brand,count,percentage,registeredUsers,appOpens,state,year,quarter,source,category,country,date,growth
0,xiaomi,11926334,0.254413,46877867,0,All,2018,1,aggregated,user,india,2018-Q1,NaN
1,samsung,9609401,0.204988,46877867,0,All,2018,1,aggregated,user,india,2018-Q1,-0.194270
2,vivo,5894293,0.125737,46877867,0,All,2018,1,aggregated,user,india,2018-Q1,-0.386612
3,oppo,4479351,0.095554,46877867,0,All,2018,1,aggregated,user,india,2018-Q1,-0.240053
4,realme,2376866,0.050703,46877867,0,All,2018,1,aggregated,user,india,2018-Q1,-0.469373

📂 map_insurance.csv

,name,count,amount,state,year,quarter,source,category,country,date,avg_transaction_value,growth
0,puducherry,112,22251.0,All,2020,2,map,insurance,india,2020-Q2,198.669643,NaN
1,tamil nadu,5473,1075552.0,All,2020,2,map,insurance,india,2020-Q2,196.519642,47.866071
2,uttar pradesh,9884,1912266.0,All,2020,2,map,insurance,india,2020-Q2,193.470862,0.805957
3,madhya pradesh,6283,1198701.0,All,2020,2,map,insurance,india,2020-Q2,190.784816,-0.364326
4,andhra pradesh,22104,3982391.0,All,2020,2,map,insurance,india,2020-Q2,180.166079,2.518065

📂 map_transaction.csv

,name,count,amount,state,year,quarter,source,category,country,date,avg_transaction_value,growth
0,puducherry,104212,1.658260e+08,All,2018,1,map,transaction,india,2018-Q1,1591.236819,NaN
1,tamil nadu,6726622,1.126156e+10,All,2018,1,map,transaction,india,2018-Q1,1674.177276,63.547480
2,uttar pradesh,12537805,1.393997e+10,All,2018,1,map,transaction,india,2018-Q1,1111.835040,0.863908
3,madhya pradesh,8025395,8.681603e+09,All,2018,1,map,transaction,india,2018-Q1,1081.766493,-0.359904
4,andhra pradesh,9039585,1.199628e+10,All,2018,1,map,transaction,india,2018-Q1,1327.082647,0.126373

📂 map_user.csv

,name,count,amount,state,year,quarter,country,date,avg_transaction_value,growth
0,puducherry,49318,0.0,All,2018,1,india,2018-Q1,0.0,NaN
1,tamil nadu,2104754,0.0,All,2018,1,india,2018-Q1,0.0,41.677197
2,uttar pradesh,4694250,0.0,All,2018,1,india,2018-Q1,0.0,1.230308
3,madhya pradesh,2553603,0.0,All,2018,1,india,2018-Q1,0.0,-0.456015
4,andhra pradesh,3336450,0.0,All,2018,1,india,2018-Q1,0.0,0.306566

📂 top_insurance.csv

,name,count,amount,state,year,quarter,source,category,level,country,date,avg_transaction_value,growth
0,maharashtra,39836,6879717.0,All,2020,2,top,insurance,states,india,2020-Q2,172.700999,NaN
1,karnataka,27358,4794150.0,All,2020,2,top,insurance,states,india,2020-Q2,175.237590,-0.313234
2,andhra pradesh,22104,3982391.0,All,2020,2,top,insurance,states,india,2020-Q2,180.166079,-0.192046
3,telangana,19003,3419453.0,All,2020,2,top,insurance,states,india,2020-Q2,179.942799,-0.140291
4,delhi,11716,1897480.0,All,2020,2,top,insurance,states,india,2020-Q2,161.956299,-0.383466

📂 top_transaction.csv

,name,count,amount,state,year,quarter,source,category,level,country,date,avg_transaction_value,growth
0,maharashtra,16387034,2.171161e+10,All,2018,1,top,transaction,states,india,2018-Q1,1324.926357,NaN
1,uttar pradesh,12537805,1.393997e+10,All,2018,1,top,transaction,states,india,2018-Q1,1111.835040,-0.234895
2,karnataka,12016899,1.921790e+10,All,2018,1,top,transaction,states,india,2018-Q1,1599.239148,-0.041547
3,west bengal,11710225,1.062598e+10,All,2018,1,top,transaction,states,india,2018-Q1,907.410281,-0.025520
4,andhra pradesh,9039585,1.199628e+10,All,2018,1,top,transaction,states,india,2018-Q1,1327.082647,-0.228061

📂 top_user.csv

,name,count,state,year,quarter,level,country,date,growth
0,maharashtra,6106994,All,2018,1,states,india,2018-Q1,NaN
1,uttar pradesh,4694250,All,2018,1,states,india,2018-Q1,-0.231332
2,karnataka,3717763,All,2018,1,states,india,2018-Q1,-0.208018
3,andhra pradesh,3336450,All,2018,1,states,india,2018-Q1,-0.102565
4,telangana,3315560,All,2018,1,states,india,2018-Q1,-0.006261

### Dataset Rows & Columns count

In [18]:
# Dataset Rows & Columns count
for file in files:
    file_path = os.path.join(output_path, file)

    print(f"\n📂 {file}")

    df = pd.read_csv(file_path)

    print("Shape:", df.shape)

📂 aggregated_insurance.csv
Shape: (701, 9)

📂 aggregated_transaction.csv
Shape: (5174, 9)

📂 aggregated_user.csv
Shape: (6919, 11)

📂 map_insurance.csv
Shape: (14558, 9)

📂 map_transaction.csv
Shape: (21612, 9)

📂 map_user.csv
Shape: (21616, 7)

📂 top_insurance.csv
Shape: (12846, 10)

📂 top_transaction.csv
Shape: (19135, 10)

📂 top_user.csv
Shape: (19136, 7)

### Dataset Information

In [20]:
# Dataset Info
for file in files:
    df = pd.read_csv(f"{output_path}/{file}")

    print(f"\n📂 {file}")
    display(df.info())

📂 aggregated_insurance.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 701 entries, 0 to 700
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   type      701 non-null    object
 1   count     701 non-null    int64
 2   amount    701 non-null    float64
 3   state     682 non-null    object
 4   year      701 non-null    int64
 5   quarter   701 non-null    int64
 6   source    701 non-null    object
 7   category  701 non-null    object
 8   country   701 non-null    object
dtypes: float64(1), int64(3), object(5)
memory usage: 49.4+ KB

None

📂 aggregated_transaction.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5174 entries, 0 to 5173
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   type      5174 non-null   object
 1   count     5174 non-null   int64
 2   amount    5174 non-null   float64
 3   state     5034 non-null   object
 4   year      5174 non-null   int64
 5   quarter   5174 non-null   int64
 6   source    5174 non-null   object
 7   category  5174 non-null   object
 8   country   5174 non-null   object
dtypes: float64(1), int64(3), object(5)
memory usage: 363.9+ KB

None

📂 aggregated_user.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6919 entries, 0 to 6918
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   brand            6919 non-null   object
 1   count            6919 non-null   int64
 2   percentage       6919 non-null   float64
 3   registeredUsers  6919 non-null   int64
 4   appOpens         6919 non-null   int64
 5   state            6732 non-null   object
 6   year             6919 non-null   int64
 7   quarter          6919 non-null   int64
 8   source           6919 non-null   object
 9   category         6919 non-null   object
 10  country          6919 non-null   object
dtypes: float64(1), int64(5), object(5)
memory usage: 594.7+ KB

None

📂 map_insurance.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14558 entries, 0 to 14557
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      14558 non-null  object
 1   count     14558 non-null  int64
 2   amount    14558 non-null  float64
 3   state     13876 non-null  object
 4   year      14558 non-null  int64
 5   quarter   14558 non-null  int64
 6   source    14558 non-null  object
 7   category  14558 non-null  object
 8   country   14558 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 1023.7+ KB

None

📂 map_transaction.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21612 entries, 0 to 21611
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      21612 non-null  object
 1   count     21612 non-null  int64
 2   amount    21612 non-null  float64
 3   state     20604 non-null  object
 4   year      21612 non-null  int64
 5   quarter   21612 non-null  int64
 6   source    21612 non-null  object
 7   category  21612 non-null  object
 8   country   21612 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 1.5+ MB

None

📂 map_user.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21616 entries, 0 to 21615
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     21616 non-null  object
 1   count    21616 non-null  int64
 2   amount   21616 non-null  int64
 3   state    20608 non-null  object
 4   year     21616 non-null  int64
 5   quarter  21616 non-null  int64
 6   country  21616 non-null  object
dtypes: int64(4), object(3)
memory usage: 1.2+ MB

None

📂 top_insurance.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12846 entries, 0 to 12845
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      12843 non-null  object
 1   count     12846 non-null  int64
 2   amount    12846 non-null  float64
 3   state     12276 non-null  object
 4   year      12846 non-null  int64
 5   quarter   12846 non-null  int64
 6   source    12846 non-null  object
 7   category  12846 non-null  object
 8   level     12846 non-null  object
 9   country   12846 non-null  object
dtypes: float64(1), int64(3), object(6)
memory usage: 1003.7+ KB

None

📂 top_transaction.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19135 entries, 0 to 19134
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      19133 non-null  object
 1   count     19135 non-null  int64
 2   amount    19135 non-null  float64
 3   state     18295 non-null  object
 4   year      19135 non-null  int64
 5   quarter   19135 non-null  int64
 6   source    19135 non-null  object
 7   category  19135 non-null  object
 8   level     19135 non-null  object
 9   country   19135 non-null  object
dtypes: float64(1), int64(3), object(6)
memory usage: 1.5+ MB

None

📂 top_user.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19136 entries, 0 to 19135
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     19136 non-null  object
 1   count    19136 non-null  int64
 2   state    18296 non-null  object
 3   year     19136 non-null  int64
 4   quarter  19136 non-null  int64
 5   level    19136 non-null  object
 6   country  19136 non-null  object
dtypes: int64(3), object(4)
memory usage: 1.0+ MB

None

#### Duplicate Values

In [22]:
# Dataset Duplicate Value Count
for file in files:
    file_path = os.path.join(output_path, file)
    df = pd.read_csv(file_path)

    print(f"\n📂 {file}")

    # Find duplicates (all columns)
    duplicates = df[df.duplicated()]

    print(" Duplicate Rows Count:", duplicates.shape[0])

    if not duplicates.empty:
        display(duplicates.head())
    else:
        print("✅ No duplicate rows found")

📂 aggregated_insurance.csv
 Duplicate Rows Count: 0
✅ No duplicate rows found

📂 aggregated_transaction.csv
 Duplicate Rows Count: 0
✅ No duplicate rows found

📂 aggregated_user.csv
 Duplicate Rows Count: 0
✅ No duplicate rows found

📂 map_insurance.csv
 Duplicate Rows Count: 0
✅ No duplicate rows found

📂 map_transaction.csv
 Duplicate Rows Count: 0
✅ No duplicate rows found

📂 map_user.csv
 Duplicate Rows Count: 0
✅ No duplicate rows found

📂 top_insurance.csv
 Duplicate Rows Count: 0
✅ No duplicate rows found

📂 top_transaction.csv
 Duplicate Rows Count: 0
✅ No duplicate rows found

📂 top_user.csv
 Duplicate Rows Count: 0
✅ No duplicate rows found

#### Missing Values/Null Values

In [25]:
# Missing Values/Null Values Count
for file in files:
    df = pd.read_csv(f"{output_path}/{file}")

    print(f"\n📂 {file}")

    summary = pd.DataFrame({
        "Column": df.columns,
        "Missing Count": df.isnull().sum(),
        "Missing %": (df.isnull().sum() / len(df)) * 100
    })

    display(summary[summary["Missing Count"] > 0])

📂 aggregated_insurance.csv

      Column  Missing Count  Missing %
state  state             19   2.710414

📂 aggregated_transaction.csv

      Column  Missing Count  Missing %
state  state            140   2.705837

📂 aggregated_user.csv

      Column  Missing Count  Missing %
state  state            187   2.702703

📂 map_insurance.csv

      Column  Missing Count  Missing %
state  state            682   4.684709

📂 map_transaction.csv

      Column  Missing Count  Missing %
state  state           1008   4.664076

📂 map_user.csv

      Column  Missing Count  Missing %
state  state           1008   4.663212

📂 top_insurance.csv

      Column  Missing Count  Missing %
name    name              3   0.023354
state  state            570   4.437179

📂 top_transaction.csv

      Column  Missing Count  Missing %
name    name              2   0.010452
state  state            840   4.389862

📂 top_user.csv

      Column  Missing Count  Missing %
state  state            840   4.389632

In [37]:
# Visualizing the missing values
import pandas as pd
import plotly.graph_objects as go
# Store missing counts
data = {}

all_columns = set()

# Collect missing values
for file in files:
    df = pd.read_csv(f"{output_path}/{file}")
    missing = (df.isnull().sum())

    data[file] = missing
    all_columns.update(missing.index)

# Convert to DataFrame
missing_df = pd.DataFrame(data).fillna(0)
missing_df = missing_df[(missing_df.sum(axis=1) > 0)]

# Create Plotly grouped bar chart
fig = go.Figure()

for col in missing_df.index:
    fig.add_trace(go.Bar(
        x=missing_df.columns,
        y=missing_df.loc[col],
        name=col
    ))

fig.update_layout(
    barmode='group',
    title="Missing Values per File (Column-wise)",
    xaxis_title="Files",
    yaxis_title="Missing Count",
    xaxis_tickangle=-90,
    height=600
)

fig.show()

### What did you know about your dataset?

The raw data contained many nested folders which contains multiple csv files.
Data folder structure :

data-scv/

│

├── aggregated/

├── map/

└── top/

    │
    ├── insurance/
    ├── transaction/
    └── user/
          │
          └── country/
                └── india/
                      ├── 2020/
                      │     ├── 1.csv
                      │     ├── 2.csv
                      │
                      ├── 2021/
                      │     ├── 1.csv
                      │
                      ├── state/
                      │     ├── karnataka/
                      │     │     ├── 1.csv
                      │     │
                      │     ├── westbengal/
                      │           ├── 1.csv
                      │
                      └── (map only)
                            └── hover/
                                  └── country/
                                        └── india/
                                              └── ...

The original hierarchical data structure is complex and time-consuming to process due to its multiple nested levels (such as country, state, year, and quarter). To streamline and improve the efficiency of the analysis process, the data has been consolidated into nine structured CSV files:


*   aggregated_insurance – Contains aggregated insurance metrics at broader levels (country/state), including summarized values such as totals across time periods.
*  aggregated_transaction – Includes aggregated transaction data such as total transaction count and amount across different regions and time periods.
*  aggregated_user – Stores aggregated user statistics, such as total registered users and app usage metrics over time.
* map_insurance – Provides geographically mapped insurance data, typically at finer levels (e.g., districts), useful for spatial analysis and visualization.
*  map_transaction – Contains transaction-related data mapped to geographic regions, enabling location-based insights into transaction volume and value.
*  map_user – Includes user-related metrics (such as app opens or user counts) mapped across different regions for geographic analysis.
*  top_insurance – Lists top-performing insurance categories or entities (e.g., policies, providers) ranked by metrics such as count or value.
*  top_transaction – Highlights top transaction categories, states, or districts based on transaction count and amount.
*  top_user – Contains top user-related segments such as leading brands, states, or districts based on user engagement or registration metrics.

Each of these files is enriched with additional metadata columns such as state, year, quarter, and country, enabling consistent filtering, grouping, and comparative analysis across all datasets.


The files do not contain any duplicate values. State column in the files conatins missing values as some files are directly under country folder without containing data related to state. The files compose variables of different data types such as object, int and float.


The dataset represents a comprehensive view of digital financial activity across India, capturing multiple dimensions such as transactions, insurance, and user engagement over time. It integrates data across various geographical levels, including country, state, and district, along with temporal attributes like year and quarter, enabling both macro-level and granular analysis. Structured into aggregated, map, and top categories, the dataset provides insights into overall trends, geographical distribution, and high-performing segments, respectively. It includes key metrics such as transaction count and value, insurance activity, and user statistics like registrations and app usage, facilitating analysis of growth patterns, regional variations, and adoption of digital financial services. Overall, the dataset serves as a robust foundation for data-driven insights, supporting trend analysis, spatial comparisons, and performance evaluation.

## ***2. Understanding Your Variables***

In [38]:
# Dataset Columns
for file in files:
    df = pd.read_csv(f"{output_path}/{file}")

    print(f"\n📂 {file}")
    print("Columns:", df.columns.tolist())

📂 aggregated_insurance.csv
Columns: ['type', 'count', 'amount', 'state', 'year', 'quarter', 'source', 'category', 'country']

📂 aggregated_transaction.csv
Columns: ['type', 'count', 'amount', 'state', 'year', 'quarter', 'source', 'category', 'country']

📂 aggregated_user.csv
Columns: ['brand', 'count', 'percentage', 'registeredUsers', 'appOpens', 'state', 'year', 'quarter', 'source', 'category', 'country']

📂 map_insurance.csv
Columns: ['name', 'count', 'amount', 'state', 'year', 'quarter', 'source', 'category', 'country']

📂 map_transaction.csv
Columns: ['name', 'count', 'amount', 'state', 'year', 'quarter', 'source', 'category', 'country']

📂 map_user.csv
Columns: ['name', 'count', 'amount', 'state', 'year', 'quarter', 'country']

📂 top_insurance.csv
Columns: ['name', 'count', 'amount', 'state', 'year', 'quarter', 'source', 'category', 'level', 'country']

📂 top_transaction.csv
Columns: ['name', 'count', 'amount', 'state', 'year', 'quarter', 'source', 'category', 'level', 'country']

📂 top_user.csv
Columns: ['name', 'count', 'state', 'year', 'quarter', 'level', 'country']

In [39]:
# Dataset Describe
for file in files:
    df = pd.read_csv(f"{output_path}/{file}")

    print(f"\n📂 {file}")
    print(df.describe())

📂 aggregated_insurance.csv
              count        amount         year     quarter
count  7.010000e+02  7.010000e+02   701.000000  701.000000
mean   4.141462e+04  5.710627e+07  2022.111270    2.577746
std    1.397228e+05  2.085979e+08     1.370777    1.092188
min    4.000000e+00  1.199000e+03  2020.000000    1.000000
25%    6.470000e+02  8.801820e+05  2021.000000    2.000000
50%    7.552000e+03  7.729792e+06  2022.000000    3.000000
75%    3.425100e+04  4.173702e+07  2023.000000    4.000000
max    1.475429e+06  2.293956e+09  2024.000000    4.000000

📂 aggregated_transaction.csv
              count        amount         year      quarter
count  5.174000e+03  5.174000e+03  5174.000000  5174.000000
mean   9.094881e+07  1.335613e+11  2021.002513     2.500773
std    6.254713e+08  1.002325e+12     1.999853     1.118142
min    2.000000e+00  3.439721e+01  2018.000000     1.000000
25%    6.363575e+04  4.423959e+07  2019.000000     2.000000
50%    5.737635e+05  4.846731e+08  2021.000000     3.000000
75%    1.361543e+07  1.255325e+10  2023.000000     4.000000
max    1.741919e+10  2.663387e+13  2024.000000     4.000000

📂 aggregated_user.csv
              count   percentage  registeredUsers      appOpens         year  \
count  6.919000e+03  6919.000000     6.919000e+03  6.919000e+03  6919.000000
mean   1.000240e+06     0.090909     1.100264e+07  2.938519e+08  2019.647059
std    4.589936e+06     0.083314     3.692268e+07  1.248509e+09     1.233982
min    1.000000e+01     0.005158     5.010000e+02  0.000000e+00  2018.000000
25%    1.020550e+04     0.020542     2.042920e+05  0.000000e+00  2019.000000
50%    9.565800e+04     0.057649     2.185938e+06  6.129766e+06  2020.000000
75%    5.216465e+05     0.146133     9.233009e+06  1.656051e+08  2021.000000
max    8.842700e+07     0.478367     3.729518e+08  1.572420e+10  2022.000000

           quarter
count  6919.000000
mean      2.411765
std       1.140713
min       1.000000
25%       1.000000
50%       2.000000
75%       3.000000
max       4.000000

📂 map_insurance.csv
               count        amount          year       quarter
count   14558.000000  1.455800e+04  14558.000000  14558.000000
mean     1994.186976  2.749770e+06   2022.132711      2.586413
std      8606.246946  1.265854e+07      1.375244      1.092255
min         1.000000  3.100000e+01   2020.000000      1.000000
25%       119.000000  1.121788e+05   2021.000000      2.000000
50%       353.000000  4.693015e+05   2022.000000      3.000000
75%      1012.750000  1.427972e+06   2023.000000      4.000000
max    183532.000000  3.058618e+08   2024.000000      4.000000

📂 map_transaction.csv
              count        amount          year       quarter
count  2.161200e+04  2.161200e+04  21612.000000  21612.000000
mean   2.177348e+07  3.197504e+10   2021.016102      2.505321
std    1.283756e+08  1.755162e+11      2.006219      1.118047
min    2.000000e+00  1.698886e+02   2018.000000      1.000000
25%    2.645662e+05  4.874546e+08   2019.000000      2.000000
50%    1.682778e+06  3.151249e+09   2021.000000      3.000000
75%    9.049750e+06  1.488478e+10   2023.000000      4.000000
max    3.634232e+09  4.151820e+12   2024.000000      4.000000

📂 map_user.csv
              count        amount          year       quarter
count  2.161600e+04  2.161600e+04  21616.000000  21616.000000
mean   8.201514e+05  3.722133e+07   2021.015544      2.505181
std    3.331194e+06  1.947957e+08      2.006452      1.118048
min    2.200000e+01  0.000000e+00   2018.000000      1.000000
25%    6.506275e+04  5.018470e+05   2019.000000      2.000000
50%    2.104180e+05  6.261351e+06   2021.000000      3.000000
75%    5.286260e+05  2.384657e+07   2023.000000      4.000000
max    7.180780e+07  5.335171e+09   2024.000000      4.000000

📂 top_insurance.csv
               count        amount          year       quarter
count   12846.000000  1.284600e+04  12846.000000  12846.000000
mean     2155.540480  2.875971e+06   2022.117001      2.580959
std      9210.953267  1.349172e+07      1.370124      1.092645
min         1.000000  3.100000e+01   2020.000000      1.000000
25%        56.000000  6.117350e+04   2021.000000      2.000000
50%       317.500000  3.448100e+05   2022.000000      3.000000
75%      1139.000000  1.440126e+06   2023.000000      4.000000
max    183532.000000  3.058618e+08   2024.000000      4.000000

📂 top_transaction.csv
              count        amount          year       quarter
count  1.913500e+04  1.913500e+04  19135.000000  19135.000000
mean   2.533323e+07  3.592516e+10   2021.002038      2.500706
std    1.404218e+08  1.902944e+11      2.000770      1.118040
min    2.000000e+00  6.025276e+01   2018.000000      1.000000
25%    1.363570e+05  2.638302e+08   2019.000000      2.000000
50%    1.149971e+06  1.813639e+09   2021.000000      3.000000
75%    8.602260e+06  1.318138e+10   2023.000000      4.000000
max    3.634232e+09  4.151820e+12   2024.000000      4.000000

📂 top_user.csv
              count          year       quarter
count  1.913600e+04  19136.000000  19136.000000
mean   7.697163e+05   2021.001881      2.500627
std    3.413571e+06      2.000835      1.118063
min    1.000000e+00   2018.000000      1.000000
25%    2.178275e+04   2019.000000      2.000000
50%    1.144985e+05   2021.000000      3.000000
75%    4.158372e+05   2023.000000      4.000000
max    7.180780e+07   2024.000000      4.000000

### Variables Description

The processed dataset is organized into nine structured CSV files, each representing different analytical perspectives—aggregated, map, and top data—across insurance, transaction, and user domains. The aggregated datasets (aggregated_insurance, aggregated_transaction, and aggregated_user) provide summarized metrics such as counts and transaction amounts, along with user-related statistics like registered users and app opens, enriched with attributes such as type, brand, source, and category. The map datasets (map_insurance, map_transaction, and map_user) capture geographically distributed data using region identifiers (name), enabling spatial analysis of counts and amounts across states and districts. The top datasets (top_insurance, top_transaction, and top_user) highlight high-performing entities or regions, incorporating ranking context through the level field. Across all files, common metadata fields such as state, year, quarter, and country ensure consistency for temporal and regional analysis. In terms of data types, numerical fields like count, amount, registeredUsers, and appOpens are stored as integers or floats, percentage values are represented as floats, while categorical attributes such as type, name, brand, state, category, source, level, and country are stored as strings. Temporal fields like year and quarter are maintained as integers, making the dataset well-structured and suitable for efficient querying, aggregation, and visualization.

### Check Unique Values for each variable.

In [8]:
# Check Unique Values for each variable.
import pandas as pd

seen_columns = set()  # to track already processed columns

for file in files:
    df = pd.read_csv(f"{output_path}/{file}")

    for column in df.columns:
        if column not in seen_columns:   # only new columns
            unique_values = df[column].unique()

            print(f"Column: {column}")
            print(f"Unique Values: {unique_values}")
            print()

            seen_columns.add(column)  # mark as seen

Column: type
Unique Values: ['Insurance']

Column: count
Unique Values: [ 923173 1010211  893850 1159063  248626  354284  185348  630758  806491
  617606 1035364   33037   23107   14406   17682   91069   79698   90690
  104871   64356   46714  125491   47621   97348  111521  116867  127002
   10290    5473    8026  103701   92458  116589   92930   64514   77022
   45996   55133   24103   44132   32799   25952   78940   73080   92125
   74194   18131   17470    9884   34848   28870   27080   28298   36325
   45600   51465   64655   54508   63993   61523   55118   64873   67388
   78498   56941   19003   34395   20961   10311   10487   11533   13090
    5773    8750    6784    5339    2607    5529    2742    4111    7856
    7552   10040    8051    1756     660    1403   77158   91719   67048
   79576   56833   58131   49792   72712   24839   26320   15200   15488
   38779   47853   33542   54277   10233   12596    7619     381     702
     494     360     249     244      88     907    1508    1590    1021
    2516    2794    2637    2188    2237    2071    1563    1642     415
      81     100     187     166     312     119     171     277     214
     489     186      76     350      85     310      31      74    1809
    1955    2447    2232    1156    1199    2331    1585    2702    2600
    2304    2838     786     526     372     561     234     112     191
   10816   13187   13777   14048   14729   16279   15509   14129    7475
    9175   12370   12187    3783    4047    6638    4887    2488    2036
    2451     418     410     568     320     268     269     331      79
     183      91     367     242     210      41      89      62   15235
    5373   12509   55241   59127   73530   64533   17800   18281   16643
   19375   49741   34415   39960   37170   40926   33975   21517   24333
    1030    1235    1313    1140     263     107     139     562     730
     806     809     379     337     600     627      92     685     400
     599     461     239     160     306     243     260     270     251
     324     106      93     122     195      67      94      21    8236
    7967    7942    9093   12371   18898    9627   24538   25065   18899
   22163   20263    7526    2981   10955   33165   27977   26524   24579
     111     145     127     136     218     271     177     200     405
     285     346     385     225     222     123     134      55      90
  119776  149016  118933  168078  102754  112174  104872  136968   90958
  125900   88015   80935   71662   44798   39836   70381   82423   55792
   52268    8893    7397    7313    7597    4071    4794    5031    3584
    1197    3113    1105    1452    4555    6264    5453    5262     647
     206     441     162     137     113      75     291     429     446
      46     192      32     161     232     215      14      33      27
  169357  174990  183532  142599   74436   37595   40969   47468  156076
  117232  127376  139699  110273  133971   93385   95640   27358   53701
   31747      26      15      12      53     159      49      18      38
      11       4       5      19   26393   29300   40784   27027   22733
   29234   13791   14629   41429   51223   59688   43248   14476   10653
    6283   15069   14427   11990   14803   37110   65563   35667   54587
    8811    1588    5479   79123   73106   65271   89533   61032   62377
   66059   73543   19199    9530    5731   10926   58808   50391   49735
   46085   14163   11038   19489   12516   37971   25352   35346   22783
   40710   47506   42815   37287    8283    7139    6321   22221   25381
   36418   31302   51049   32600   32484   41128   46763   62526   44007
   44665   14676   15348   12673   19142    7697    9990   12525    9477
   14388    9373   16779    5180    4879    8465    6794   22224   29079
   23629   24824   16108   19478   22398   16662    2063    3659    5368
    2768    3641    4565    2831    5430    6697    5272    5194    2474
    1064    1759    1210    3935    4197    5211    3909     531     710
     392     378     338     149     264    1520    1883    1767    1704
    1330     792    1533    1730    1991    2095    1798     999    1100
     842    1147     718     606     696     613     510     355     564
     194     204     212      65     135     125   35944   28232   48908
   26378   16679   12822   13292   34251   47113   45821   56336   41358
   46189   49150   53050   67962    9725   11716    7588   33097   21805
   22368   17633   22100   22593   23168   16475    3167    8622    4495
    3265   14149   16230    9228   18826    2413     978    2206    1008
    1503    1052    1295     368     467     421     438     871     493
     707     799     694    1207     969     257     651    1371    1293
    1191    1097     501     901     768     643     230     757    1004
    1145     795     124       6    6662    5354    5021    5225    1016
     879    1214    2087    3157    2634    4388    3524    3927    4883
    4166    4097     341     683     614   22723   19579   15724   16550
   10514   17300   11927   10460    6612    8849   11994    7008    5055
    4676    6029    4712    1346    3757    4702   41798   43150   34920
   36376   29954   44329   39301   32185   25423   33205   23075   22105
   42547   46582   48014   61425   49812   22104   21464   33895   20253
   21892   28511   26929   29212   36550   41447   49101   51592   44745
   62662   12554   22456   14301   18030    9733    9913    2816  374867
  318119  363989  526327 1475429 1105041 1273789 1213629]

Column: amount
Unique Values: [1.40880122e+09 1.44523468e+09 1.34739987e+09 1.85529977e+09
 1.70979933e+08 8.94950760e+07 3.37321660e+07 8.57034846e+08
 1.05471787e+09 8.87447241e+08 1.43976274e+09 4.21842900e+07
 2.34029180e+07 1.11808490e+07 1.64443440e+07 1.14625593e+08
 1.05328191e+08 1.16710222e+08 1.39433796e+08 7.97475200e+07
 6.18351200e+07 1.46457790e+08 6.49690450e+07 1.35972378e+08
 1.48976175e+08 1.62128271e+08 1.73784251e+08 8.99357500e+06
 1.07555200e+06 2.25737300e+06 1.76442664e+08 1.59894258e+08
 1.99179867e+08 1.57303596e+08 8.77035120e+07 1.16755813e+08
 7.30149690e+07 7.74349530e+07 1.80275730e+07 5.96549510e+07
 3.26411180e+07 2.51375710e+07 1.21483170e+08 1.27110494e+08
 1.65509877e+08 1.22522457e+08 4.43696900e+06 1.41804170e+07
 1.91226600e+06 3.88454920e+07 2.09356510e+07 2.09252170e+07
 1.48109470e+07 5.19420160e+07 5.80569560e+07 6.47981260e+07
 8.85441270e+07 8.26782070e+07 1.05605522e+08 8.43974650e+07
 7.92389680e+07 1.10715264e+08 1.05607539e+08 1.24755619e+08
 9.60373040e+07 3.41945300e+06 8.40654300e+06 1.13390990e+07
 1.77544470e+07 1.78601440e+07 1.95314830e+07 2.33675490e+07
 9.16831300e+06 1.38177470e+07 1.00701720e+07 8.82494800e+06
 2.71932700e+06 7.84902000e+06 3.26571700e+06 4.64657100e+06
 1.26367490e+07 1.35990260e+07 1.90451520e+07 1.40349150e+07
 1.96189100e+06 1.34899000e+05 4.18543000e+05 1.07451766e+08
 1.20602777e+08 8.94766330e+07 1.04987909e+08 7.74617320e+07
 7.63593120e+07 6.52042800e+07 1.00365562e+08 2.14243370e+07
 3.12828710e+07 1.23960290e+07 1.11720420e+07 5.11605270e+07
 5.90923070e+07 4.17370210e+07 7.04664330e+07 7.51045500e+06
 2.87848200e+06 1.43276400e+06 4.09934000e+05 1.02250800e+06
 6.49961000e+05 1.91531000e+05 6.16420000e+04 1.49765000e+05
 2.20540000e+04 1.49340100e+06 2.11253400e+06 2.10598400e+06
 1.50910500e+06 3.32334300e+06 3.76573200e+06 3.41756800e+06
 2.86948900e+06 3.16974100e+06 2.89939300e+06 2.16381300e+06
 2.40495800e+06 3.02841000e+05 8.36410000e+04 1.75847000e+05
 1.24805000e+05 2.71799000e+05 5.57950000e+05 2.32928000e+05
 3.26688000e+05 4.27693000e+05 3.31455000e+05 8.11687000e+05
 2.75746000e+05 1.15090000e+05 6.12551000e+05 1.89428000e+05
 4.71306000e+05 7.32200000e+03 2.46910000e+04 1.19124000e+05
 2.61400600e+06 2.59309100e+06 3.41939500e+06 2.89164700e+06
 1.59778600e+06 1.66340400e+06 2.69313000e+06 2.02552900e+06
 3.79355400e+06 3.96852300e+06 3.32299700e+06 3.89603300e+06
 9.46607000e+05 5.08277000e+05 3.51827000e+05 5.56442000e+05
 1.97955000e+05 2.22510000e+04 5.83990000e+04 2.33309660e+07
 2.49981750e+07 2.87158280e+07 2.44614880e+07 2.82139400e+07
 3.18789870e+07 3.01110340e+07 2.71643970e+07 1.31556820e+07
 1.54653670e+07 1.93818950e+07 2.17278310e+07 2.55838000e+06
 3.76891900e+06 9.91282800e+06 5.27155900e+06 6.84753000e+05
 3.99452000e+05 1.88429100e+06 6.85292000e+05 8.20539000e+05
 9.25684000e+05 1.16841700e+06 7.04957000e+05 6.32287000e+05
 6.28890000e+05 8.22973000e+05 4.29730000e+04 1.39479000e+05
 3.41424000e+05 1.23643000e+05 7.00864000e+05 5.29223000e+05
 4.39669000e+05 3.80878000e+05 9.79100000e+03 2.07980000e+04
 3.88360000e+04 3.75852700e+06 1.09593300e+06 6.47157300e+06
 9.55046570e+07 1.02926410e+08 1.27930986e+08 1.08827800e+08
 8.07422500e+06 1.43574450e+07 1.27938620e+07 2.44552620e+07
 9.47016520e+07 6.14410500e+07 6.43287840e+07 6.13014490e+07
 6.07928380e+07 4.55655440e+07 3.15769320e+07 3.37489310e+07
 1.98710700e+06 2.31800700e+06 2.49365600e+06 2.44387800e+06
 4.51612000e+05 1.28776000e+05 1.48434000e+05 2.14554000e+05
 1.18752300e+06 1.55157700e+06 1.84336400e+06 1.72807600e+06
 7.89094000e+05 7.29211000e+05 1.03949100e+06 1.18952900e+06
 3.36150000e+04 7.10290000e+04 8.82900000e+03 1.59055400e+06
 8.80182000e+05 1.38168000e+06 1.02939800e+06 6.85987000e+05
 3.83709000e+05 6.67214000e+05 4.74940000e+05 6.88605000e+05
 6.28191000e+05 6.98251000e+05 7.93745000e+05 1.40552000e+05
 1.22064000e+05 1.11777000e+05 5.03532000e+05 7.02140000e+04
 2.80000000e+04 4.78900000e+03 4.38333000e+06 6.00868600e+06
 5.83292400e+06 1.09416260e+07 1.66310950e+07 2.33085310e+07
 1.45393090e+07 3.35654010e+07 3.97533920e+07 2.93605550e+07
 3.13071100e+07 2.90083500e+07 4.20870100e+06 6.15193000e+05
 2.64019100e+06 4.69732240e+07 4.00324950e+07 4.06086510e+07
 3.68404740e+07 1.33016000e+05 2.71789000e+05 8.13320000e+04
 7.22540000e+04 5.53649000e+05 6.20655000e+05 5.17854000e+05
 4.03213000e+05 8.26159000e+05 5.87893000e+05 6.47411000e+05
 6.85052000e+05 4.76626000e+05 6.32084000e+05 3.41671000e+05
 1.93021000e+05 4.51640000e+04 1.25540000e+04 4.90570000e+04
 2.01319952e+08 2.24725389e+08 1.98945046e+08 2.66942711e+08
 1.57303399e+08 1.66596248e+08 1.51171882e+08 2.17657114e+08
 1.13835208e+08 1.74915648e+08 1.17411928e+08 1.04603934e+08
 1.92301560e+07 2.71138140e+07 6.87971700e+06 4.67631030e+07
 9.32622270e+07 3.31377530e+07 4.13133070e+07 1.82521100e+07
 1.42377070e+07 1.46951820e+07 1.55546350e+07 7.72979200e+06
 8.28182600e+06 1.01111830e+07 7.24426700e+06 1.83208900e+06
 5.22331700e+06 1.54628800e+06 2.13913300e+06 1.02758770e+07
 1.39323090e+07 1.09758740e+07 1.09748390e+07 7.34861000e+05
 4.84840000e+04 1.33339000e+05 4.10091000e+05 3.69742000e+05
 2.69446000e+05 1.93935000e+05 9.64349000e+05 6.14435000e+05
 9.70334000e+05 9.78637000e+05 8.62510000e+04 1.74052000e+05
 1.95966000e+05 3.45300000e+04 4.95736000e+05 6.49027000e+05
 6.35831000e+05 7.18967000e+05 2.53800000e+03 1.02600000e+04
 3.42060000e+04 2.64708700e+08 2.87393291e+08 3.05861806e+08
 2.39304982e+08 9.07232880e+07 3.01833250e+07 3.95010060e+07
 4.80783660e+07 2.48056311e+08 1.75704013e+08 1.86543426e+08
 1.99448538e+08 1.44605784e+08 1.85063287e+08 1.23228632e+08
 1.30733580e+08 4.79415000e+06 1.24073940e+07 2.68149680e+07
 3.01990000e+04 3.83840000e+04 1.24070000e+04 7.83460000e+04
 1.85542000e+05 3.36300000e+04 1.29350000e+04 5.53120000e+04
 2.74630000e+04 3.46640000e+04 2.71350000e+04 4.15040000e+04
 1.70960000e+04 5.22500000e+03 6.96200000e+03 1.60340000e+04
 1.19900000e+03 4.51356790e+07 4.69633480e+07 7.38010700e+07
 4.48717640e+07 2.91851180e+07 4.27128830e+07 1.99014620e+07
 2.01590980e+07 7.38366670e+07 8.52159820e+07 1.01096769e+08
 7.79956680e+07 3.49612600e+06 4.89712400e+06 1.19870100e+06
 1.75244320e+07 5.56792700e+06 7.80625800e+06 9.78739100e+06
 6.41721900e+07 1.03982997e+08 5.99202030e+07 8.53909240e+07
 2.83036100e+06 3.60216000e+05 4.44552500e+06 1.31721699e+08
 1.15101791e+08 1.08142369e+08 1.44083113e+08 1.00620604e+08
 1.01786828e+08 1.10021582e+08 1.21905046e+08 3.12603190e+07
 9.67658800e+06 5.04050600e+06 1.32556460e+07 9.43165120e+07
 8.18165090e+07 7.91986420e+07 7.47798790e+07 1.32158980e+07
 7.29788000e+06 2.58858380e+07 1.12724530e+07 5.66271150e+07
 3.37590680e+07 4.54028000e+07 3.25269430e+07 6.21860660e+07
 8.07471590e+07 6.17823110e+07 6.11271940e+07 5.97427800e+06
 1.88486800e+06 1.17981400e+06 2.99534330e+07 3.20909650e+07
 5.06293250e+07 3.75572270e+07 6.57680850e+07 4.69376940e+07
 4.62540950e+07 6.67354460e+07 7.09503270e+07 9.18581050e+07
 6.38664630e+07 6.26339100e+07 1.02639980e+07 1.23419030e+07
 7.28810400e+06 2.32829210e+07 1.43059100e+06 6.05503700e+06
 3.33581200e+06 1.34648400e+07 1.81568570e+07 1.38194660e+07
 2.31478050e+07 5.08423000e+06 3.27485100e+06 1.11904230e+07
 7.04604800e+06 3.22451290e+07 4.22536140e+07 3.43531460e+07
 3.43329900e+07 2.38234060e+07 2.51657020e+07 3.34846440e+07
 2.32162150e+07 4.05031000e+05 2.85702400e+06 1.34993400e+06
 5.23473900e+06 6.16169200e+06 9.06043600e+06 5.37107800e+06
 1.04332540e+07 1.40905230e+07 1.05389990e+07 1.00087050e+07
 4.66766100e+06 9.06492000e+05 2.44454500e+06 1.40233800e+06
 7.86976700e+06 8.49942500e+06 1.18988240e+07 7.82613300e+06
 1.65559000e+05 6.30966000e+05 7.79360000e+04 3.10943000e+05
 4.69634000e+05 2.38576000e+05 8.35813000e+05 2.95370000e+04
 7.09690000e+04 1.53341000e+05 2.41557400e+06 2.66063000e+06
 3.05393400e+06 2.50110700e+06 1.87495900e+06 2.02452800e+06
 1.15093200e+06 1.99843900e+06 3.14398400e+06 3.44573800e+06
 3.72993200e+06 3.17731500e+06 2.35947200e+06 2.41970000e+06
 1.95138500e+06 2.35301500e+06 2.10540800e+06 1.90478600e+06
 1.74747500e+06 2.09598800e+06 1.46457200e+06 1.30030400e+06
 8.94107000e+05 1.36023100e+06 1.31611000e+05 2.24928000e+05
 3.71051000e+05 5.98459000e+05 1.43290000e+04 3.96870000e+04
 8.42470000e+04 4.15701600e+07 3.54420690e+07 6.06031730e+07
 3.17872810e+07 1.50070790e+07 9.65526100e+06 1.08409290e+07
 3.65783310e+07 5.88785000e+07 6.10400380e+07 7.73324010e+07
 5.49511080e+07 6.80460720e+07 7.11394890e+07 7.62323460e+07
 9.43907280e+07 8.04544200e+06 1.89748000e+06 1.92728500e+06
 4.81072480e+07 3.53362290e+07 3.47966030e+07 3.13889710e+07
 3.69638880e+07 3.56181580e+07 3.87317340e+07 2.83681390e+07
 2.33441900e+06 1.39620680e+07 6.01086500e+06 3.00812200e+06
 2.25435640e+07 2.74477660e+07 1.53578110e+07 2.92391680e+07
 1.80680100e+06 2.10034000e+05 5.99450000e+05 1.36725900e+06
 2.29252900e+06 1.60286900e+06 1.90850900e+06 2.73596000e+05
 2.75638000e+05 2.85691000e+05 4.25384000e+05 6.86857000e+05
 1.27262800e+06 7.20741000e+05 9.83776000e+05 1.21516800e+06
 1.05875300e+06 1.97386700e+06 1.33310300e+06 6.55040000e+04
 1.49513000e+05 1.01029000e+05 1.96455600e+06 2.02638000e+06
 1.75280000e+06 1.74469400e+06 7.79740000e+05 1.44121000e+06
 1.13128700e+06 9.02466000e+05 3.05235000e+05 1.81504000e+05
 2.44266000e+05 1.05638000e+06 1.23339500e+06 1.43919800e+06
 1.75782100e+06 1.25114500e+06 1.53800000e+04 1.57975000e+05
 1.36000000e+03 9.90337400e+06 8.05169000e+06 7.17855800e+06
 7.52809300e+06 1.02833900e+06 8.27384000e+05 1.38598600e+06
 2.73731600e+06 4.14210800e+06 3.86524500e+06 6.19066900e+06
 5.09351000e+06 5.64605400e+06 7.41100100e+06 5.93080100e+06
 5.85954900e+06 7.11000000e+04 1.96864000e+05 6.82364000e+05
 3.74211650e+07 3.00832590e+07 2.59357430e+07 2.77240600e+07
 1.63896100e+07 2.97046730e+07 1.78383820e+07 1.65771910e+07
 1.01391900e+07 1.21194700e+07 1.81378560e+07 1.01199640e+07
 3.81341700e+06 3.56883700e+06 8.22903900e+06 2.62046800e+06
 2.79005000e+05 2.24990100e+06 1.39365600e+06 6.23424230e+07
 5.78023960e+07 5.19633550e+07 5.20674780e+07 4.26481570e+07
 5.80432390e+07 4.87919310e+07 4.17080720e+07 3.16103350e+07
 2.27306870e+07 1.99143380e+07 1.27498740e+07 6.29482810e+07
 6.35638020e+07 7.39151990e+07 8.00289140e+07 1.24264810e+07
 3.98239100e+06 1.29856320e+07 4.39145190e+07 2.77557360e+07
 2.82128330e+07 3.47042510e+07 3.87467110e+07 4.03548860e+07
 4.58323550e+07 5.76243220e+07 6.52850650e+07 6.38444420e+07
 6.27772860e+07 8.37398000e+07 8.79661900e+06 2.73138130e+07
 1.33015810e+07 1.82349410e+07 2.16110200e+06 7.86093200e+06
 5.95621000e+05 3.42403352e+08 2.06307024e+08 2.95066678e+08
 6.55431877e+08 2.29395629e+09 1.75962789e+09 1.93195565e+09
 1.94126564e+09]

Column: state
Unique Values: [nan 'tamil-nadu' 'uttar-pradesh' 'telangana' 'uttarakhand' 'west-bengal'
 'tripura' 'mizoram' 'puducherry' 'punjab' 'nagaland' 'rajasthan'
 'meghalaya' 'sikkim' 'odisha' 'manipur' 'maharashtra' 'jammu-&-kashmir'
 'ladakh' 'karnataka' 'lakshadweep' 'madhya-pradesh' 'kerala' 'haryana'
 'gujarat' 'jharkhand' 'himachal-pradesh' 'chandigarh' 'arunachal-pradesh'
 'delhi' 'assam' 'dadra-&-nagar-haveli-&-daman-&-diu'
 'andaman-&-nicobar-islands' 'goa' 'chhattisgarh' 'andhra-pradesh' 'bihar']

Column: year
Unique Values: [2023 2020 2022 2021 2024]

Column: quarter
Unique Values: [1 3 2 4]

Column: source
Unique Values: ['aggregated']

Column: category
Unique Values: ['insurance']

Column: country
Unique Values: ['india']

Column: brand
Unique Values: ['Xiaomi' 'Vivo' 'Samsung' 'Oppo' 'Realme' 'Apple' 'OnePlus' 'Motorola'
 'Huawei' 'Tecno' 'Others' 'Lenovo' 'Infinix' 'Asus' 'Micromax' 'Gionee'
 'Lava' 'HMD Global' 'COOLPAD' 'Lyf']

Column: percentage
Unique Values: [0.23710032 0.20706324 0.17666284 ... 0.02068968 0.0191597  0.10155569]

Column: registeredUsers
Unique Values: [372951831  21919787  17979979  16808799  19323278  20644527  13222022
  15662093  14448366  11960822   9643222   7449425   8612795  10885058
   4851740   3833795   2604789   6279278   2148567   1943606   2365438
   2596244   3674829   3004040   3233509   2802122   3460015   1224955
   1585859   1752677   1414339    649142    810612   1012103    483043
  22150612  20917649  17149069  18306880  19615278  10090557   9046007
  11220691   7963425  12306860  14590882  15927797  13378191   4260115
   5138501   6529679   3315560  17661088  18980985  21977202  20499465
  16329494  13563201  14969412  12142053  23398857  10925031   9797304
   7712204   8783935   5175453   3158202   4212964   6358738    439636
    546292    509929    472153    582124    409110    336666    376731
    299962    245456    272298    217644    183254     55157    116874
     83369    153265    396609    346279    423167    369961    255600
    230908    285173    319626    156458    177868    133059    204292
    109494     49318     81546     65580    448051  20136256  22498519
  27249134  24838116  38999692  14316349  12458661  17949542  16044607
  36617655  29482075  34151882  31651894   4694250   6442554  10341964
   8096483  21667020  10872368  13643451  12150786  15357586   8428835
   9620493   7429609   6296303  20433142  19127440  16632608  17804542
   2996036   5199878   3900177   2104754    104631    148543    134773
    119921    160213    197407    171740    184693     82128     92972
     70999     58956    209616     48538     28097     37637     20051
   5976548   6434862   6880103   5568777   4225481   3739502   5157868
   4694233   2600112   3321742   2962713   2226590   7302726   1865715
   1473148   1152190    847142     80077     93124     53911     66891
    173106    192188    130205    107143    223337    259990    207808
    241797    276483     32090     42997     22436     15074   2795718
   1594015   3623911   2185781   7258315   6652970   7901755   8598751
  12124779   4845359   6115537   5387209   4320744   9233009   9891029
  10652490  11399235    223065    240268    190869    205686    255839
     74746     87395    100030     61487    136211    157741    113814
    176447     49634     26618     18513     37281   2279329   2604854
   3281371   2915511    885762   1532362   1230599   1913949   4061035
   4480027   4917938   3651393   7025275   5313049   6151843   6596196
   5701503   8972299   3503938   2990963   2550167   2136624   5582300
   4078316   6387169   4728844   1757326    784184   1347598   1066587
   7949425   6936943   8473810   7416083  19656147   6414403   8180664

## 3. ***Data Wrangling***

### Data Wrangling Code

In [7]:
# Write your code to make your dataset analysis ready.
# Handling missing values
df["state"] = df["state"].fillna("All")
df["country"] = df["country"].fillna("india")

In [8]:
# Standardize Categorical Values and handle missing values across all dataframes
import os
import pandas as pd

for file_name in files:
    file_path = os.path.join(output_path, file_name)
    df = pd.read_csv(file_path)

    print(f"\nProcessing {file_name} for standardization...")

    # Define a list of columns that might exist and need standardization
    columns_to_standardize_lower = ["type", "name", "brand", "state", "category", "source", "level", "country"]
    columns_to_standardize_title = ["state"] # only state needs title case (after lowercasing)

    # Apply lowercase standardization
    for col in columns_to_standardize_lower:
        if col in df.columns and df[col].dtype == 'object':
            df[col] = df[col].str.lower()

    # Apply title case standardization for 'state'
    for col in columns_to_standardize_title:
        if col in df.columns and df[col].dtype == 'object':
            # Ensure 'state' is converted to title case after lowercasing
            df[col] = df[col].str.title()

    # Handle missing values for state and country, which were identified as having NaNs
    if "state" in df.columns:
        df["state"] = df["state"].fillna("All") # 'All' is Title case now for consistency
    if "country" in df.columns:
        df["country"] = df["country"].fillna("India") # 'India' is Title case now for consistency

    # Save the modified dataframe back to its original path
    df.to_csv(file_path, index=False)
    print(f"Standardization and missing value handling applied and saved for {file_name}")

Processing aggregated_insurance.csv for standardization...
Standardization and missing value handling applied and saved for aggregated_insurance.csv

Processing aggregated_transaction.csv for standardization...
Standardization and missing value handling applied and saved for aggregated_transaction.csv

Processing aggregated_user.csv for standardization...
Standardization and missing value handling applied and saved for aggregated_user.csv

Processing map_insurance.csv for standardization...
Standardization and missing value handling applied and saved for map_insurance.csv

Processing map_transaction.csv for standardization...
Standardization and missing value handling applied and saved for map_transaction.csv

Processing map_user.csv for standardization...
Standardization and missing value handling applied and saved for map_user.csv

Processing top_insurance.csv for standardization...
Standardization and missing value handling applied and saved for top_insurance.csv

Processing top_transaction.csv for standardization...
Standardization and missing value handling applied and saved for top_transaction.csv

Processing top_user.csv for standardization...
Standardization and missing value handling applied and saved for top_user.csv

In [9]:
# Correcting data types across all dataframes
import os
import pandas as pd

for file_name in files:
    file_path = os.path.join(output_path, file_name)
    df = pd.read_csv(file_path)

    print(f"\nProcessing {file_name} for data type correction...")

    # Convert 'year' and 'quarter' to integer if they exist
    if "year" in df.columns:
        df["year"] = df["year"].astype(int)
    if "quarter" in df.columns:
        df["quarter"] = df["quarter"].astype(int)

    # Convert 'count' and 'amount' to numeric, coercing errors
    if "count" in df.columns:
        df["count"] = pd.to_numeric(df["count"], errors='coerce')
    if "amount" in df.columns:
        df["amount"] = pd.to_numeric(df["amount"], errors='coerce')

    # Save the modified dataframe back to its original path
    df.to_csv(file_path, index=False)
    print(f"Data type correction applied and saved for {file_name}")

Processing aggregated_insurance.csv for data type correction...
Data type correction applied and saved for aggregated_insurance.csv

Processing aggregated_transaction.csv for data type correction...
Data type correction applied and saved for aggregated_transaction.csv

Processing aggregated_user.csv for data type correction...
Data type correction applied and saved for aggregated_user.csv

Processing map_insurance.csv for data type correction...
Data type correction applied and saved for map_insurance.csv

Processing map_transaction.csv for data type correction...
Data type correction applied and saved for map_transaction.csv

Processing map_user.csv for data type correction...
Data type correction applied and saved for map_user.csv

Processing top_insurance.csv for data type correction...
Data type correction applied and saved for top_insurance.csv

Processing top_transaction.csv for data type correction...
Data type correction applied and saved for top_transaction.csv

Processing top_user.csv for data type correction...
Data type correction applied and saved for top_user.csv

In [10]:
# Feature engineering
for file_name in files:
    df = pd.read_csv(f"{output_path}/{file_name}")

    print(f"\nProcessing {file_name}...")
    # Creating new features
    if "year" in df.columns and "quarter" in df.columns:
        df["date"] = df["year"].astype(str) + "-Q" + df["quarter"].astype(str)

    if "amount" in df.columns and "count" in df.columns:
        df["avg_transaction_value"] = df["amount"] / df["count"].replace(0, pd.NA)

    # Determining growth
    if "count" in df.columns:
        df = df.sort_values(by=["state", "year", "quarter"])
        df["growth"] = df.groupby("state")["count"].pct_change()

    # Handling outliers
    if "amount" in df.columns:
        upper_limit = df["amount"].quantile(0.99)
        df["amount"] = df["amount"].clip(upper=upper_limit)

    # Save back
    df.to_csv(f"{output_path}/{file_name}", index=False)

Processing aggregated_insurance.csv...

Processing aggregated_transaction.csv...

Processing aggregated_user.csv...

Processing map_insurance.csv...

Processing map_transaction.csv...

Processing map_user.csv...

Processing top_insurance.csv...

Processing top_transaction.csv...

Processing top_user.csv...

### What all manipulations have you done and insights you found?

The dataset initially existed in a complex, hierarchical structure with multiple nested folders, making direct analysis difficult and time-consuming. To address this, the data was consolidated into nine structured CSV files based on three categories—aggregated, map, and top—across insurance, transaction, and user domains. During this process, important metadata such as state, year, quarter, and country was extracted from file paths and appended as columns. This step was essential to transform unstructured file-based information into structured attributes, enabling consistent filtering, grouping, and comparison across all datasets.

Several data cleaning and preprocessing techniques were applied to improve data quality and ensure reliability. Missing values in the state and country columns were handled by filling them with “All” and “India” respectively, which preserved the meaning of country-level data instead of leaving gaps that could disrupt analysis. Standardization of categorical variables such as state, type, category, and source was performed to eliminate inconsistencies in naming (e.g., different cases or formats), ensuring accurate grouping and aggregation. Data type correction was also necessary, as converting year and quarter into integers and numerical fields like count and amount into numeric formats enabled proper calculations and prevented errors during analysis.

Feature engineering techniques were applied to enhance the analytical depth of the data. A date column was created by combining year and quarter, allowing easier time-series analysis and trend identification. The average transaction value was derived to better understand transaction behavior beyond just total counts and amounts, while growth rates were calculated to measure changes over time and identify trends across states. Outlier handling using percentile-based capping was implemented to reduce the influence of extreme values, ensuring that the analysis was not skewed by anomalies. Data reshaping using pivot tables further improved usability by organizing the data into a format suitable for comparisons across different dimensions such as states and years.

These techniques collectively contributed to transforming raw, inconsistent data into a clean, structured, and analysis-ready format. As a result, meaningful insights could be derived more effectively. The analysis revealed a consistent upward trend in digital financial activity, indicating increasing adoption over time. Regional variations highlighted disparities in adoption levels across states, while top-performing datasets identified leading regions and categories. User engagement metrics such as registered users and app opens also showed steady growth, reflecting increased usage of digital platforms. Overall, the applied data wrangling and transformation techniques not only improved data quality but also enabled accurate, insightful, and reliable analysis.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1

In [18]:
# Chart - 1 visualization code
import pandas as pd
import plotly.express as px

# Example: use one dataset (change file if needed)
df = pd.read_csv(f"{output_path}/aggregated_transaction.csv")

# Ensure correct types
df["year"] = df["year"].astype(int)

# Group data
yearly_data = df.groupby("year")["amount"].sum().reset_index()

# Plot
fig = px.line(
    yearly_data,
    x="year",
    y="amount",
    markers=True,
    title="Total Transaction Amount per Year"
)

fig.show()

##### 1. Why did you pick the specific chart?

This chart helps in understanding the total amount of money transacted per year. A line chart effectively highlights the overall trend, making it easier to observe patterns of growth or decline over time. It allows for clear visualization of year-on-year changes, helping identify whether the transaction value is consistently increasing, decreasing, or showing fluctuations, thereby providing insights into the adoption and expansion of digital financial activities.

##### 2. What is/are the insight(s) found from the chart?

The trend line indicates a significant and consistent increase in the total amount transacted over the years. Starting from approximately ₹3 trillion in 2018, the transaction value has grown rapidly to around ₹145 trillion by 2024. This sharp upward trend reflects the widespread adoption and expansion of digital financial services, highlighting a strong growth trajectory in transaction volume and overall economic activity in the digital payments ecosystem.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, by analyzing the trend over years, meaningful business impact can be achieved. Observing a consistent increase in transaction amounts indicates strong market growth and rising adoption of digital financial services. This helps businesses gain confidence in investing in the sector, scaling operations, and introducing new products or services. It also supports long-term planning by showing whether the market is expanding or stagnating.

Additionally, if there are periods where the growth curve flattens or shows minor dips, it may indicate temporary reductions in transaction activity due to external factors such as economic conditions, policy changes, or reduced consumer spending. Such patterns highlight that despite an overall upward trend, growth is not always uniform and may face periods of stagnation.

Therefore, while the long-term trend is positive, these subtle variations emphasize the need for continuous innovation and strategic efforts to sustain growth and avoid potential slowdowns in the future.

#### Chart - 2

In [33]:
# Chart - 2 visualization code
import pandas as pd
import plotly.express as px

df = pd.read_csv(f"{output_path}/aggregated_transaction.csv")

# Get top 5 states by total amount
top_states = df.groupby("state")["amount"].sum().nlargest(5).index
df_filtered = df[df["state"].isin(top_states)]

# Group data
state_year = df_filtered.groupby(["year", "state"])["amount"].sum().reset_index()
state_total = df.groupby("state")["amount"].sum().reset_index()
# Plot
fig = px.bar(
    state_total.sort_values(by="amount", ascending=False).head(10),
    x="state",
    y="amount",
    title="Top States by Transaction Amount",
    color_discrete_sequence=["firebrick"]
)

fig.show()

##### 1. Why did you pick the specific chart?

The bar chart helps in understanding how the transaction amount varies across different regions. It provides a clear comparison of states, making it easy to identify which regions contribute the most and which have lower transaction volumes. This visualization highlights regional disparities in digital financial activity and helps in recognizing high-performing areas as well as regions with potential for growth.

##### 2. What is/are the insight(s) found from the chart?

The chart shows that transaction amounts vary significantly across different states. A few states, such as Telangana and Maharashtra, record substantially higher transaction values, reaching up to around ₹39 trillion. In contrast, states like West Bengal and Bihar have comparatively lower transaction amounts, approximately ₹15 trillion. This highlights a clear regional disparity in digital financial activity, with certain states contributing more prominently to the overall transaction volume than others.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights can contribute to a positive business impact. Understanding that certain states like Telangana and Maharashtra have significantly higher transaction volumes helps businesses focus their efforts on high-performing regions for maximizing returns. At the same time, identifying states like West Bengal and Bihar with comparatively lower transaction amounts highlights untapped markets where businesses can expand and increase adoption through targeted strategies. This regional insight enables better resource allocation, more effective marketing, and data-driven decision-making, ultimately supporting business growth and improved market reach.

Also, a strong concentration of transactions in a few high-performing states like Telangana and Maharashtra may create an over-dependence on these regions. This imbalance can be risky, as any slowdown or market saturation in these states could negatively impact overall performance. Therefore, while high-performing regions drive current growth, the underperformance in other regions highlights the need for balanced expansion strategies to ensure sustainable and inclusive business growth.

#### Chart - 3

In [13]:
# Chart - 3 visualization code
import pandas as pd
import plotly.express as px

df = pd.read_csv(f"{output_path}/aggregated_transaction.csv")

# Group by quarter
quarter_data = df.groupby("quarter")["amount"].sum().reset_index()

# Sort quarters properly
quarter_data = quarter_data.sort_values("quarter")

# Convert to label (optional)
quarter_year = df.groupby(["year", "quarter"])["amount"].sum().reset_index()

fig = px.line(
    quarter_year,
    x="quarter",
    y="amount",
    color="year",
    markers=True,
    title="Quarter-wise Transaction Trend Across Years"
)

fig.show()

##### 1. Why did you pick the specific chart?

This chart illustrates the variation in transaction amounts across quarters for each year, highlighting the increase or decrease in activity within different periods. It enables a clearer understanding of seasonal trends by showing how transaction values fluctuate from one quarter to another over time. By comparing these patterns, the chart helps identify which quarters consistently demonstrate stronger performance, thereby providing insights into periods of higher digital financial activity.

##### 2. What is/are the insight(s) found from the chart?

The analysis indicates that Quarter 4 consistently outperforms the other quarters, recording the highest transaction amounts across years. In contrast, Quarter 1 shows relatively lower performance, with transaction values being consistently lower compared to subsequent quarters. This pattern suggests a clear seasonal trend where transaction activity gradually increases as the year progresses, peaking towards the end. It reflects higher financial activity in later quarters, possibly driven by factors such as festive seasons, increased consumer spending, and year-end financial closures.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights can create a positive business impact. Identifying that Quarter 4 consistently performs the best allows businesses to strategically plan for peak demand by increasing marketing efforts, optimizing inventory, and scaling operations during this period to maximize revenue. At the same time, recognizing that Quarter 1 shows weaker performance helps businesses take corrective actions, such as introducing promotions, discounts, or targeted campaigns to boost activity during slower periods. Overall, understanding these seasonal patterns enables better resource allocation, improved planning, and more effective decision-making, ultimately enhancing business performance and growth.

Additionally, any irregular fluctuations or slower growth rates between consecutive quarters may signal instability or stagnation in user activity. Such trends could arise due to factors like reduced user engagement, lack of new incentives, or external economic conditions. Therefore, while the overall trend shows growth, these periodic declines highlight the importance of proactive strategies to maintain consistent performance throughout the year and prevent potential negative impacts on business growth.

#### Chart - 4

In [22]:
# Chart - 4 visualization code
import pandas as pd
import plotly.express as px

df = pd.read_csv(f"{output_path}/aggregated_user.csv")

# Group by brand
brand_data = df.groupby("brand").agg({
    "registeredUsers": "sum",
    "appOpens": "sum"
}).reset_index()

# Plot
fig = px.scatter(
    brand_data,
    x="registeredUsers",
    y="appOpens",
    color="brand",
    size="registeredUsers",
    title="User Engagement: Registered Users vs App Opens",
    labels={
        "registeredUsers": "Registered Users",
        "appOpens": "App Opens"
    }
)

fig.update_layout(title_x=0.5)

fig.show()

##### 1. Why did you pick the specific chart?

This chart represents the user engagement ratio across different brands by comparing the number of registered users with the number of app opens. It highlights how actively users interact with each brand’s platform. A scatter plot is well suited for this analysis, as it clearly shows the relationship between the two variables, making it easier to identify patterns such as high user base with strong engagement or cases where engagement is relatively low compared to registrations.

##### 2. What is/are the insight(s) found from the chart?

Users show higher engagement on the platform for brands such as Xiaomi, Motorola, Huawei, and Apple, as indicated by a strong relationship between registered users and app opens. In contrast, brands like Infinix, Asus, Lava, and Coolpad exhibit relatively lower interaction levels, suggesting weaker user engagement despite their presence on the platform. This highlights differences in how actively users of various brands utilize the application.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, the gained insights can contribute to a positive business impact. Understanding that certain brands such as Xiaomi, Motorola, Huawei, and Apple show higher user engagement allows businesses to strengthen partnerships, optimize app performance for these devices, and target loyal user segments more effectively. At the same time, identifying lower engagement in brands like Infinix, Asus, Lava, and Coolpad helps in recognizing areas that require improvement, such as app optimization, targeted marketing, or user experience enhancements. This enables better resource allocation and more focused strategies to improve overall platform usage.

However, the insights also indicate areas that may lead to negative growth if not addressed. Lower user engagement in certain brands suggests that users may not be actively interacting with the platform despite being registered. This could be due to factors such as poor app performance on those devices, lack of awareness, or limited accessibility. If these issues persist, it may result in reduced user retention and slower growth in those segments

#### Chart - 5

In [14]:
# Chart - 5 visualization code
import pandas as pd
import plotly.express as px

df = pd.read_csv(f"{output_path}/aggregated_user.csv")

# Group data (to avoid duplicates)
brand_state = df.groupby(["state", "brand"])["percentage"].mean().reset_index()

# Plot
import pandas as pd
import plotly.express as px

df = pd.read_csv(f"{output_path}/aggregated_user.csv")

# ❌ Remove 'All'
df = df[df["state"] != "All"]

# Group data
brand_state = df.groupby(["state", "brand"])["percentage"].mean().reset_index()

# Plot
fig = px.bar(
    brand_state,
    x="state",
    y="percentage",
    color="brand",
    barmode="stack",
    title="Distribution of Brands per State"
)

# Add spacing
fig.update_layout(
    bargap=0.3,
    title_x=0.5
)

fig.show()

##### 1. Why did you pick the specific chart?

The chart illustrates the distribution of user percentages across different brands for each state. It highlights how brand preferences vary regionally, with certain brands dominating in specific states while others have a smaller share. This helps in understanding market penetration and user preference patterns across regions.

##### 2. What is/are the insight(s) found from the chart?

Brands such as Xiaomi, Vivo, and Samsung dominate across most states, indicating a significantly higher share of users and stronger market presence. In contrast, brands like Gionee and Huawei contribute a much smaller proportion, reflecting lower user adoption and engagement. This highlights a clear disparity in brand popularity, with a few leading brands capturing the majority of the user base across regions.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights can create a positive business impact. Identifying that brands like Xiaomi, Vivo, and Samsung dominate across most states allows businesses to focus on these high-performing segments through strategic partnerships, targeted marketing, and optimized app performance to maximize user engagement and revenue. At the same time, understanding brand-wise distribution across states helps in tailoring region-specific strategies and improving customer experience.

However the low contribution from brands like Gionee and Huawei suggests weaker user adoption and engagement on these devices. This could be due to factors such as limited market presence, lower device usage, or possible compatibility and performance issues with the platform. If these gaps are not addressed, it may result in missed opportunities for user expansion and reduced overall growth potential. Additionally, heavy reliance on a few dominant brands could pose a risk if their user base declines, making it important to diversify engagement across a wider range of brands for sustainable growth.

#### Chart - 6

In [20]:
# Chart - 6 visualization code
import pandas as pd
import plotly.express as px

df = pd.read_csv(f"{output_path}/aggregated_user.csv")

# Group data properly
brand_year = df.groupby(["year", "brand"])["count"].sum().reset_index()

# Convert to percentage per year
brand_year["percentage"] = brand_year.groupby("year")["count"].transform(lambda x: x / x.sum() * 100)

# Pivot for heatmap
pivot = brand_year.pivot(index="brand", columns="year", values="percentage")

# Plot heatmap
fig = px.imshow(
    pivot,
    aspect="auto",
    title="Brand-wise User Percentage Heatmap (Year vs Brand)",
    labels=dict(x="Year", y="Brand", color="Percentage"),
    color_continuous_scale="Viridis"
)

fig.show()

##### 1. Why did you pick the specific chart?

The heatmap visualizes the distribution of user percentages across different brands over the years. It highlights that certain brands consistently maintain higher user shares, as indicated by darker color intensities, while others show lower contributions. The relatively consistent color patterns across years suggest stable brand dominance with limited variation in user preferences over time.

##### 2. What is/are the insight(s) found from the chart?

A few brands such as Xiaomi, Samsung, and Vivo consistently show high contributions across all years, indicating strong and stable user preference. In contrast, lower-performing brands exhibit minimal contribution and show little to no improvement over time, reflecting limited growth and weaker adoption among users.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights can create a positive business impact. Identifying that brands like Xiaomi, Samsung, and Vivo consistently maintain high user share enables businesses to focus on these dominant segments through targeted partnerships, optimized app performance, and focused marketing strategies to maximize engagement and revenue. It also helps in understanding stable market preferences, allowing for better long-term planning and resource allocation.

However, the insights also reveal potential areas that may lead to negative growth. The lack of improvement among lower-performing brands indicates stagnant or declining user adoption in those segments. This could be due to factors such as limited market presence, lower device usage, or suboptimal app performance on those devices. If these issues are not addressed, it may result in missed opportunities for user expansion. Additionally, heavy dependence on a few dominant brands poses a risk—any decline in their user base could significantly impact overall performance. Therefore, while the insights highlight strong growth areas, they also emphasize the need to improve engagement across a wider range of brands to ensure balanced and sustainable growth.

#### Chart - 7

In [18]:
# Chart - 7 visualization code
import pandas as pd
import plotly.express as px

df = pd.read_csv(f"{output_path}/aggregated_transaction.csv")

# Group by transaction type
type_count = df.groupby("type")["count"].sum().reset_index()

# Plot donut chart
fig = px.pie(
    type_count,
    names="type",
    values="count",
    hole=0.4,
    title="Transaction Count Distribution by Type",
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig.show()

##### 1. Why did you pick the specific chart?

This chart represents the distribution of transaction amounts across different categories of transactions. It shows that certain categories, such as merchant payments, account for a significantly higher number of transactions, while categories like financial services contribute a comparatively smaller share. The donut chart effectively visualizes this distribution, making it easy to compare the proportion of each category and understand which transaction types dominate overall activity.

##### 2. What is/are the insight(s) found from the chart?

Merchant payments account for the largest share of transactions, contributing to more than 50% of the total. Categories such as peer-to-peer payments and recharge and bill payments show a moderate level of activity, indicating steady user engagement. In contrast, categories like financial services and other segments contribute only a small portion to the overall transactions, reflecting relatively lower adoption in these areas.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights can create a strong positive business impact. Identifying that merchant payments dominate with over 50% contribution helps businesses prioritize and strengthen this segment through targeted marketing, partnerships, and infrastructure improvements to maximize revenue. At the same time, recognizing that peer-to-peer and recharge/bill payments have moderate usage allows companies to maintain engagement while exploring ways to further enhance user experience and adoption. Additionally, categories like financial services with low contribution highlight untapped opportunities, where businesses can introduce new features, awareness campaigns, or incentives to drive growth. Overall, these insights enable better strategic focus, efficient resource allocation, and data-driven decision-making, ultimately supporting business expansion and increased profitability.

#### Chart - 8

In [21]:
# Chart - 8 visualization code
import pandas as pd
import plotly.express as px

df = pd.read_csv(f"{output_path}/top_transaction.csv")

# Group by level
level_count = df.groupby("level")["count"].sum().reset_index()

# Plot
fig = px.pie(
    level_count,
    names="level",
    values="count",
    title="Transaction Distribution by Level"
)

fig.show()

##### 1. Why did you pick the specific chart?

The chart shows the distribution of transaction counts across different levels. It highlights which level contributes the most to overall transactions, indicating where the majority of activity is concentrated. This helps in understanding whether transactions are more dominant at broader or more granular levels.

##### 2. What is/are the insight(s) found from the chart?

District-level transactions account for the highest count compared to state-level and pincode-level transactions. This indicates that transaction activity is more concentrated at a granular, district level, reflecting finer regional engagement and higher localized usage of digital financial services.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights can create a positive business impact. Identifying that district-level transactions have the highest count indicates that user activity is more concentrated at a granular level. This enables businesses to design localized strategies, such as region-specific marketing campaigns, partnerships with local merchants, and targeted promotions, which can significantly improve user engagement and transaction volume. It also helps in optimizing resource allocation by focusing efforts where user activity is highest. However while strong district-level activity is beneficial, businesses must also focus on improving adoption across all levels to ensure balanced and sustainable growth.

#### Chart - 9

In [28]:
# Chart - 9 visualization code
import pandas as pd
import plotly.express as px

df = pd.read_csv(f"{output_path}/top_transaction.csv")

# Clean
df["name"] = df["name"].str.strip().str.lower()
df["level"] = df["level"].str.strip().str.lower()

# Filter districts
df_district = df[df["level"].str.contains("district")]

# Group
growth_data = df_district.groupby("name")["growth"].mean().reset_index()

# Sort
growth_data = growth_data.sort_values(by="growth", ascending=False)

# Plot
fig = px.bar(
    growth_data.head(15),
    x="name",
    y="growth",
    color="growth",
    color_continuous_scale="RdYlGn",
    title="Average Growth Rate per District"
)

fig.update_layout(title_x=0.5)

fig.show()

##### 1. Why did you pick the specific chart?

The chart illustrates the average growth rate of transactions across districts, enabling the identification of regions with strong growth as well as those showing slower or declining performance. It highlights emerging districts with increasing transaction activity and underperforming areas that may require attention. Overall, it provides a clear view of regional growth patterns, supporting better understanding of future potential and areas for improvement.

##### 2. What is/are the insight(s) found from the chart?

Dadra and Nagar Haveli exhibits a higher growth rate compared to other districts, indicating a rapid increase in transaction activity and strong emerging potential in that region. In contrast, districts such as Kolkata and Khordha show relatively lower growth rates, suggesting slower expansion or possible stagnation in transaction activity. This highlights a clear variation in regional growth patterns across districts.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights can create a positive business impact. Identifying districts like Dadra and Nagar Haveli with high growth enables businesses to focus on emerging markets, invest early, and capitalize on increasing digital adoption. At the same time, recognizing variations in growth across districts helps in designing region-specific strategies, optimizing resource allocation, and improving overall market penetration.

However, the insights also indicate potential negative growth areas. Districts such as Kolkata and Khordha, which show lower growth rates, may be experiencing stagnation or slower adoption of digital transactions. This could be due to factors like market saturation, limited user engagement, or infrastructural and awareness gaps. If these issues are not addressed, it may lead to reduced growth potential and missed opportunities in these regions. Therefore, while high-growth districts offer expansion opportunities, low-growth regions require targeted interventions to prevent long-term negative impact on overall business performance.

#### Chart - 10

In [37]:
# Chart - 10 visualization code
import pandas as pd
import plotly.graph_objects as go

# Growth calculation
df["growth"] = df.groupby("state")["count"].pct_change()
growth_year = df.groupby("year")["growth"].mean().reset_index()

# Trend assignment (fixed logic)
growth_year["trend"] = 0

for i in range(len(growth_year)):
    if i == 0:
        growth_year.loc[i, "trend"] = 1
    else:
        if growth_year.loc[i, "growth"] >= growth_year.loc[i-1, "growth"]:
            growth_year.loc[i, "trend"] = 1
        else:
            growth_year.loc[i, "trend"] = -1


fig = go.Figure()

# Build segments
start = 0

for i in range(1, len(growth_year)):
    if growth_year.loc[i, "trend"] != growth_year.loc[i-1, "trend"]:

        segment = growth_year.iloc[start:i+1]

        color = "green" if growth_year.loc[i-1, "trend"] == 1 else "red"

        fig.add_trace(go.Scatter(
            x=segment["year"],
            y=segment["growth"],
            mode="lines+markers",
            line=dict(color=color),
            showlegend=False
        ))

        start = i

# last segment
segment = growth_year.iloc[start:]
color = "green" if growth_year.loc[len(growth_year)-1, "trend"] == 1 else "red"

fig.add_trace(go.Scatter(
    x=segment["year"],
    y=segment["growth"],
    mode="lines+markers",
    line=dict(color=color),
    showlegend=False
))

fig.update_layout(
    title="Overall Growth Trend (Year-wise Comparison)",
    xaxis_title="Year",
    yaxis_title="Growth"
)

fig.show()

##### 1. Why did you pick the specific chart?

A line chart is used to represent the overall growth trend as it effectively captures changes over time. It helps in visualizing fluctuations in growth rates across years, making it easier to identify patterns such as periods of increase, decline, or stability in transaction activity.

##### 2. What is/are the insight(s) found from the chart?

The chart indicates that the overall growth rate of transactions increased steadily up to 2021, reflecting a period of rapid expansion and rising adoption of digital transactions. After 2021, there is a slight decline in growth, suggesting a slowdown in the rate at which transactions are increasing. This may indicate that the market is gradually stabilizing or approaching maturity after a phase of strong growth.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights can create a positive business impact. The steady increase in growth up to 2021 indicates a strong expansion phase in digital transactions, suggesting high user adoption and increasing market potential. Businesses can leverage this by investing in scaling operations, enhancing infrastructure, and introducing new features or services during such high-growth periods to maximize returns.

However, the slight decline in growth after 2021 points to a potential slowdown in the rate of expansion. This may indicate market saturation, changing user behavior, or external economic influences. While it does not necessarily mean a decline in total transactions, it suggests that growth is stabilizing. If not addressed, this could eventually lead to reduced momentum in user acquisition and engagement. Therefore, businesses need to focus on innovation, user retention strategies, and expanding into untapped markets to sustain growth and prevent any long-term negative impact.

#### Chart - 11

In [38]:
# Chart - 11 visualization code
import pandas as pd
import plotly.express as px

df = pd.read_csv(f"{output_path}/aggregated_transaction.csv")

# remove nulls if any
df = df.dropna(subset=["count", "amount"])

fig = px.scatter(
    df,
    x="count",
    y="amount",
    trendline="ols",
    title="Relationship Between Transaction Count and Amount",
    opacity=0.6
)

fig.update_layout(title_x=0.5)

fig.show()

##### 1. Why did you pick the specific chart?

This scatter plot analyzes the relationship between transaction count and total amount. It helps determine whether higher transaction volumes lead to higher monetary value, indicating the strength of correlation between user activity and revenue generation.

##### 2. What is/are the insight(s) found from the chart?

Although transaction count is increasing over time, the total amount remains relatively constant, indicating a shift toward smaller-value transactions. However, the trendline shows a slight upward movement, suggesting a weak positive correlation between count and amount. This implies that increased user activity does not proportionally translate into higher revenue, highlighting a change in transaction behavior toward more frequent but lower-value payments.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, the insights can contribute to a positive business impact. The increasing transaction count suggests higher user engagement and growing platform adoption, which is a strong indicator of business expansion. Even if the total transaction amount remains relatively constant, sustained growth in usage provides opportunities to introduce new monetization strategies such as premium services, targeted offers, or value-added features to increase revenue in the long term.

However, there are also insights that may indicate potential negative growth concerns. Since the amount is not increasing proportionally with the transaction count, it suggests a shift toward lower-value transactions. This means users are performing more transactions but spending less per transaction, which can reduce overall revenue efficiency. If this trend continues, it may lead to stagnation in revenue growth despite rising platform activity. Therefore, while engagement is improving, businesses need to focus on increasing transaction value or improving monetization strategies to avoid long-term revenue slowdown.

#### Chart - 12

In [46]:
# Chart - 12 visualization code
import pandas as pd
import plotly.express as px

df = pd.read_csv(f"{output_path}/aggregated_transaction.csv")

# 🔹 Clean text columns
df["state"] = df["state"].str.strip().str.title()
df["type"] = df["type"].str.strip().str.title()

# 🔹 Remove ALL invalid aggregate rows
df = df[
    (df["type"].str.lower() != "all") &
    (df["state"].str.lower() != "all")
]

# 🔹 Check how many states remain
print("Unique states:", df["state"].nunique())

# 🔹 Group again
state_type = df.groupby(["state", "type"])["count"].sum().reset_index()

fig = px.bar(
    state_type,
    x="state",
    y="count",
    color="type",
    barmode="stack",
    title="Transaction Type Distribution Across States"
)

fig.update_layout(title_x=0.5)

fig.show()

Unique states: 36

##### 1. Why did you pick the specific chart?

This visualization shows the distribution of different transaction types across states. It helps identify dominant transaction behaviors in each region and highlights variations in user activity patterns, indicating whether states are primarily driven by peer-to-peer payments, merchant transactions, or other categories.

##### 2. What is/are the insight(s) found from the chart?

Based on the previous findings and the insights from this chart, the top-performing states exhibit a higher diversity and volume of transaction types, along with significantly larger transaction counts. This indicates stronger user engagement and broader adoption of digital payment methods in these regions compared to lower-performing states.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, the insights from the analysis can contribute to a positive business impact by highlighting that top-performing states have higher transaction counts along with a greater variety of transaction types, indicating strong user adoption and engagement with digital payment systems. This enables businesses to focus on these high-performing regions for expansion, optimize service delivery, and introduce targeted financial products based on user behavior, ultimately improving revenue and operational efficiency. At the same time, the insights also indicate potential negative growth concerns, as lower-performing states show fewer transactions and limited transaction diversity, suggesting weaker adoption of digital payment systems. This uneven distribution may lead to over-dependence on a few dominant states, creating a risk of stagnation if those markets saturate, while underperforming regions may continue to lag due to lack of awareness, infrastructure, or trust, thereby limiting overall business growth potential.

#### Chart - 13

In [50]:
# Chart - 13 visualization code
import pandas as pd
import plotly.express as px

user_df = pd.read_csv(f"{output_path}/aggregated_user.csv")
txn_df = pd.read_csv(f"{output_path}/aggregated_transaction.csv")
user_df["brand"] = user_df["brand"].str.strip().str.title()
txn_df["type"] = txn_df["type"].str.strip().str.title()
merged = pd.merge(
    user_df,
    txn_df,
    on=["state", "year", "quarter"],   # adjust if needed
    how="inner"
)
brand_type = merged.groupby(
    ["brand", "type"]
)["count_y"].sum().reset_index()   # txn count usually becomes count_y after merge
fig = px.bar(
    brand_type,
    x="brand",
    y="count_y",
    color="type",
    barmode="stack",
    title="Transaction Type Distribution Across Brands",
    color_discrete_map={
        "Recharge": "#1f77b4",
        "Bill Payment": "#ff7f0e",
        "Merchant Payment": "#2ca02c",
        "Peer To Peer": "#d62728",
        "Others": "#9467bd"
    }
)

fig.update_layout(title_x=0.5)

fig.show()

##### 1. Why did you pick the specific chart?

This visualization highlights the distribution of transaction types across different brands, showing how user activity varies by brand ecosystem. Leading brands typically exhibit higher transaction counts across multiple categories, indicating stronger user engagement and wider adoption of digital payment services.

##### 2. What is/are the insight(s) found from the chart?

Top brands tend to use and generate a higher volume of the most popular transaction types, indicating that dominant brands are strongly associated with the most commonly used digital payment methods. This shows that user engagement is concentrated around a few leading brands, which also drive the majority of high-frequency transaction categories compared to smaller brands that show lower usage across all transaction types.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, the insights can help create a positive business impact because they show that top brands are associated with the most frequently used transaction types, indicating strong user engagement and higher trust in leading platforms. This helps businesses focus on strengthening partnerships with dominant brands, optimizing services for high-demand transaction types, and improving marketing strategies to further increase adoption and transaction volume. However, there are also insights that could indicate potential negative growth, as smaller brands show significantly lower usage across all transaction types, which reflects a lack of diversification and heavy dependence on a few top brands. This creates a risk where overall transaction growth could slow down if these dominant brands lose engagement or reach market saturation, while underperforming brands continue to lag due to low adoption and limited user base expansion.

#### Chart - 14 - Correlation Heatmap

In [51]:
# Correlation Heatmap visualization code
import pandas as pd
import plotly.express as px

# Load your dataset
df = pd.read_csv(f"{output_path}/aggregated_transaction.csv")

# --------- Keep only numeric columns ----------
numeric_df = df[[
    "count",
    "amount",
    "avg_transaction_value"
]]

# If you have extra derived features, you can add them like:
# df["avg_transaction_value"] = df["amount"] / df["count"]
# numeric_df["avg_transaction_value"] = df["avg_transaction_value"]

# --------- Correlation matrix ----------
corr = numeric_df.corr()

# --------- Heatmap ----------
fig = px.imshow(
    corr,
    text_auto=True,
    color_continuous_scale="RdBu_r",  # good diverging palette
    zmin=-1,
    zmax=1,
    title="Correlation Heatmap"
)

fig.update_layout(title_x=0.5)

fig.show()

##### 1. Why did you pick the specific chart?

A correlation heatmap was chosen because it is specifically designed to represent the strength and direction of relationships between multiple numerical variables in a dataset. In this analysis, variables such as transaction count, amount, growth, and average transaction value were considered, and the relationships among them needed to be evaluated simultaneously. The data was visualized in a matrix format where correlation coefficients were represented using color intensity, allowing strong positive, weak, or negative relationships to be easily identified. Unlike bar or line charts, which are used for comparisons or trend analysis, the heatmap was selected as it enables multiple variable relationships to be analyzed at once, making hidden patterns and dependencies in the data easier to interpret for business decision-making.

##### 2. What is/are the insight(s) found from the chart?

A strong positive correlation between transaction count and amount indicates that as user activity increases, revenue also increases proportionally, reflecting a healthy and scalable ecosystem. This suggests effective user engagement and consistent monetization. On the other hand, weak or inconsistent correlation highlights inefficiencies where increased activity does not translate into higher revenue, indicating possible gaps in transaction value, user quality, or monetization strategy that need to be addressed for improved business performance.

#### Chart - 15 - Pair Plot

In [52]:
# Pair Plot visualization code
import pandas as pd
import plotly.express as px

# Load dataset
df = pd.read_csv(f"{output_path}/aggregated_transaction.csv")

# Create derived feature if not present
df["avg_transaction_value"] = df["amount"] / df["count"]

# Keep only numeric columns
numeric_df = df[[
    "count",
    "amount",
    "avg_transaction_value"
]].dropna()

# Pair plot
fig = px.scatter_matrix(
    numeric_df,
    dimensions=["count", "amount", "avg_transaction_value"],
    title="Pair Plot: Transaction Features",
    opacity=0.6
)

fig.update_layout(title_x=0.5)

fig.show()

##### 1. Why did you pick the specific chart?

A pair plot was used to visualize pairwise relationships between transaction count, amount, and average transaction value. This helped identify correlation patterns, distribution behavior, and potential outliers across transaction features, enabling a deeper understanding of user activity and revenue dynamics.

##### 2. What is/are the insight(s) found from the chart?

The pair plot shows that transaction count and amount generally move together, indicating a positive relationship between user activity and revenue generation. However, the relationship is not perfectly linear, as some points show high transaction counts with relatively lower amounts, suggesting variations in transaction value across regions or users. The average transaction value also does not increase consistently with count or amount, which indicates that higher activity does not always translate into higher-value transactions. Additionally, a few outliers are observed where either count or amount is significantly higher than the general trend, highlighting regions or user groups with unusual transaction behavior that may require further analysis.

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

To achieve the business objectives, the client should adopt a data-driven strategy across user behavior, geography, transactions, and time-based trends to improve growth, efficiency, and decision-making.

User data should be segmented based on spending behavior, transaction frequency, and average transaction value to enable personalized marketing and targeted engagement strategies. This will help in identifying high-value users, medium users, and low-activity users, allowing businesses to design customized offers and retention strategies. For fraud detection, unusual spikes or deviations in transaction patterns should be continuously monitored using anomaly detection techniques to ensure secure and reliable payment systems.

Geographical analysis should be leveraged to identify high-performing states and districts as well as underpenetrated regions. This enables focused expansion strategies, better resource allocation, and improved market penetration. Payment performance should be evaluated across different transaction types to understand which categories are driving growth and where optimization is required to enhance platform offerings.

User engagement metrics such as app opens, transaction frequency, and activity trends should be continuously monitored to improve retention and satisfaction through targeted campaigns and feature improvements. In addition, product development strategies should be guided by user behavior insights to enhance existing features and introduce new functionalities aligned with customer needs.

Insurance-related transaction insights should be analyzed separately to identify growth opportunities and improve product positioning within that segment. Marketing efforts should be optimized using behavioral and regional insights to improve conversion rates and return on investment. Trend analysis over time should be used to forecast demand patterns and support long-term strategic planning, while competitive benchmarking across regions and categories will help identify strengths, weaknesses, and areas requiring improvement for sustained business growth.

# **Conclusion**

The analysis of transaction and user data provides clear insights into user behavior, regional performance, brand dominance, and overall platform growth trends. It was observed that a few states and brands contribute significantly to the majority of transactions, indicating strong regional concentration and brand preference. Transaction patterns also show that higher user activity generally aligns with increased transaction volume, although revenue growth is not always proportional, highlighting variations in transaction value behavior. Over time, fluctuations in growth trends and average transaction values suggest changing user engagement patterns that require continuous monitoring.

Overall, these insights can be effectively utilized to support data-driven decision-making across multiple business areas such as customer segmentation, marketing optimization, product development, and regional expansion strategies. By leveraging these findings, businesses can enhance user engagement, improve monetization strategies, identify underperforming regions, and ensure sustainable long-term growth.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***